tables:
  employee:
    primaryKeyColumn: "employee_id"
    fields:
      - avroField: "employeeId"
        dbField: "employee_id"
        dbDatatype: "int"
      - avroField: "firstName"
        dbField: "first_name"
        dbDatatype: "string"
      - avroField: "lastName"
        dbField: "last_name"
        dbDatatype: "string"
      - avroField: "department"
        dbField: "department"
        dbDatatype: "string"
      - avroField: "salary"
        dbField: "salary"
        dbDatatype: "double"
      - avroField: "hireDate"
        dbField: "hire_date"
        dbDatatype: "timestamp"
      - avroField: "isActive"
        dbField: "is_active"
        dbDatatype: "boolean"
    deleteCondition: "employee_id = ?"
